[2022-08-31 13:44:43,230] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_to_gcs_yellow_task scheduled__2022-08-30T00:00:00+00:00 [queued]>
[2022-08-31 13:44:43,239] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: gcs_2_bq_dag.gcs_to_gcs_yellow_task scheduled__2022-08-30T00:00:00+00:00 [queued]>
[2022-08-31 13:44:43,239] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 13:44:43,239] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-08-31 13:44:43,239] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 13:44:43,253] {taskinstance.py:1259} INFO - Executing <Task(GCSToGCSOperator): gcs_to_gcs_yellow_task> on 2022-08-30 00:00:00+00:00
[2022-08-31 13:44:43,259] {standard_task_runner.py:52} INFO - Started process 2414 to run task
[2022-08-31 13:44:43,262] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'gcs_to_gcs_yellow_task', 'scheduled__2022-08-30T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/gcs_2_bq_dag.py', '--cfg-path', '/tmp/tmp5k8lfijy', '--error-file', '/tmp/tmp12_d3ikz']
[2022-08-31 13:44:43,262] {standard_task_runner.py:77} INFO - Job 146: Subtask gcs_to_gcs_yellow_task
[2022-08-31 13:44:43,311] {logging_mixin.py:109} INFO - Running <TaskInstance: gcs_2_bq_dag.gcs_to_gcs_yellow_task scheduled__2022-08-30T00:00:00+00:00 [running]> on host 0aad59a5352b
[2022-08-31 13:44:43,375] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=gcs_2_bq_dag
AIRFLOW_CTX_TASK_ID=gcs_to_gcs_yellow_task
AIRFLOW_CTX_EXECUTION_DATE=2022-08-30T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-30T00:00:00+00:00
[2022-08-31 13:44:43,376] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2022-08-31 13:44:43,376] {gcs_to_gcs.py:346} INFO - Delimiter ignored because wildcard is in prefix
[2022-08-31 13:44:43,806] {gcs_to_gcs.py:431} INFO - Executing copy of gs://dtc_data_lake_polynomial-land/raw/yellow_tripdata/2019-01/yellow_tripdata_2019-01.parquet to gs://dtc_data_lake_polynomial-land/yellow/yellow_tripdata_2019-01.parquet
[2022-08-31 13:44:44,036] {gcs.py:251} INFO - Total Bytes: 110439634 | Bytes Written: 110439634
[2022-08-31 13:44:44,036] {gcs.py:264} INFO - Object raw/yellow_tripdata/2019-01/yellow_tripdata_2019-01.parquet in bucket dtc_data_lake_polynomial-land rewritten to object yellow/yellow_tripdata_2019-01.parquet in bucket dtc_data_lake_polynomial-land
[2022-08-31 13:44:44,153] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 274, in execute
    self._copy_source_with_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 380, in _copy_source_with_wildcard
    hook=hook, source_object=source_object, destination_object=destination_object
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 437, in _copy_single_object
    hook.delete(self.source_bucket, source_object)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 643, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 793, in delete
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 1611, in delete_blob
    _target_object=None,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 662, in _delete_resource
    _target_object=_target_object,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/dtc_data_lake_polynomial-land/o/raw%2Fyellow_tripdata%2F2019-01%2Fyellow_tripdata_2019-01.parquet?prettyPrint=false: No such object: dtc_data_lake_polynomial-land/raw/yellow_tripdata/2019-01/yellow_tripdata_2019-01.parquet
[2022-08-31 13:44:44,167] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=gcs_2_bq_dag, task_id=gcs_to_gcs_yellow_task, execution_date=20220830T000000, start_date=20220831T134443, end_date=20220831T134444
[2022-08-31 13:44:44,183] {standard_task_runner.py:92} ERROR - Failed to execute job 146 for task gcs_to_gcs_yellow_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 274, in execute
    self._copy_source_with_wildcard(hook=hook, prefix=prefix)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 380, in _copy_source_with_wildcard
    hook=hook, source_object=source_object, destination_object=destination_object
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_gcs.py", line 437, in _copy_single_object
    hook.delete(self.source_bucket, source_object)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 643, in delete
    blob.delete()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 793, in delete
    retry=retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/bucket.py", line 1611, in delete_blob
    _target_object=None,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 662, in _delete_resource
    _target_object=_target_object,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 DELETE https://storage.googleapis.com/storage/v1/b/dtc_data_lake_polynomial-land/o/raw%2Fyellow_tripdata%2F2019-01%2Fyellow_tripdata_2019-01.parquet?prettyPrint=false: No such object: dtc_data_lake_polynomial-land/raw/yellow_tripdata/2019-01/yellow_tripdata_2019-01.parquet
[2022-08-31 13:44:44,196] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-08-31 13:44:44,232] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
